# Generated by Django 6.0.3 on 2026-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hp', models.IntegerField(default=100, verbose_name='Здоровье')),
                ('difficulty', models.IntegerField(choices=[(1, 'Легкий'), (2, 'Средний'), (3, 'Сложный')], default=1, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
    ]
