# Generated by Django 6.0.3 on 2026-03-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='monster_type',
            field=models.CharField(choices=[('fire', '🔥 Огненный'), ('water', '💧 Водный'), ('earth', '🌍 Земляной'), ('air', '💨 Воздушный')], default='fire', max_length=20, verbose_name='Тип монстра'),
        ),
    ]
