# Generated by Django 6.0.3 on 2026-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_monster_monster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Когда монстр должен быть побеждён', null=True, verbose_name='Срок выполнения'),
        ),
    ]
