# Generated by Django 6.0.3 on 2026-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_monster_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='defeated',
            field=models.BooleanField(default=False, verbose_name='Побеждён?'),
        ),
        migrations.AddField(
            model_name='monster',
            name='defeated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата победы'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
    ]
