# Generated by Django 6.0.3 on 2026-03-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField(verbose_name='Нанесённый урон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата атаки')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='monsters.monster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
