# Generated by Django 6.0.3 on 2026-03-06 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0006_battlelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
